### ISSUE TITLE
Always use caching

### ISSUE THREAD

**Issue by frwiqueueit** [drupal-modules/queueit#3]
This needs to be fixed. If not, it will cause issues, while download of config will follow the number of people (requests) hitting your website. We (queue-it) can't guarantee that all these requests for integration configurations will be allowed by firewall etc. (while this is not normal behavior).

https://github.com/drupal-modules/queueit/blob/8de3ec69b8483fa397952fe6935ade49a7e4b997/src/classes/QueueitKnownUser.php#L202

**Comment by kenorb** [comment]
I've pushed some caching changes which I already had, you can see them in PR (GH-4), it's almost completed. We haven't deployed it yet. We'll need to test them.

**Comment by kenorb** [comment]
GH-4 with cache fixes has been merged.
This will be deployed to NT somewhere this week.
